# Generated by Django 3.1.7 on 2021-11-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hike_name', models.CharField(max_length=50)),
                ('hike_difficulty', models.IntegerField(default=3)),
                ('hike_traffic', models.IntegerField(default=3)),
                ('hike_rating', models.IntegerField(default=4)),
            ],
        ),
    ]
