# Generated by Django 3.2.8 on 2021-11-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hike',
            name='hike_images',
            field=models.CharField(default='', max_length=50),
        ),
    ]
