# Generated by Django 3.2.8 on 2021-11-07 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hike',
            name='hike_traffic',
        ),
        migrations.AddField(
            model_name='hike',
            name='hike_description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='hike',
            name='hike_location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='hike',
            name='hike_route',
            field=models.CharField(default='', max_length=500),
        ),
    ]
