# Generated by Django 3.2.8 on 2021-11-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hike',
            name='hike_elevation',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='hike',
            name='hike_length',
            field=models.IntegerField(default=2),
        ),
    ]
