# Generated by Django 3.2.8 on 2021-11-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20211105_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='hike',
            name='hike_rating',
            field=models.IntegerField(default=4),
        ),
    ]
