# Generated by Django 3.2.8 on 2021-11-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_traffic'),
    ]

    operations = [
        migrations.AddField(
            model_name='traffic',
            name='date',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='traffic',
            name='hikeID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='traffic',
            name='num_people_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='traffic',
            name='num_people_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='traffic',
            name='num_people_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='traffic',
            name='num_people_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='traffic',
            name='num_people_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='traffic',
            name='num_people_6',
            field=models.IntegerField(default=0),
        ),
    ]
