# Generated by Django 3.2.8 on 2021-11-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20211106_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='hike',
            name='hike_duration',
            field=models.IntegerField(default=2),
        ),
    ]
