# Generated by Django 3.2.8 on 2021-11-07 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_hike_hike_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='hike_duration',
            field=models.TimeField(),
        ),
    ]
