# Generated by Django 3.2.8 on 2021-11-07 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_hike_hike_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='hike_duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hike',
            name='hike_length',
            field=models.FloatField(default=2),
        ),
    ]
