# Generated by Django 3.2.8 on 2021-11-07 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hikes_finishes',
            field=models.IntegerField(default=0),
        ),
    ]
